// Grammar topic data loading. Each topic's theory/drills JSON is registered
// below via a static `new URL("...", import.meta.url)` call rather than
// built dynamically from the topics manifest, because the GitHub Pages
// deploy workflow's cache-busting step only recognizes that literal call
// shape when appending a version query string - a dynamically constructed
// URL would silently miss out on cache-busting.

const TOPICS_URL = new URL("../data/grammarTopics.json", import.meta.url);

const THEORY_URLS = {
  tenses: new URL("../data/tenses.json", import.meta.url),
  articles: new URL("../data/articles.json", import.meta.url),
  modals: new URL("../data/modals.json", import.meta.url),
  passive: new URL("../data/passive.json", import.meta.url),
  plurals: new URL("../data/plurals.json", import.meta.url),
  possessives: new URL("../data/possessives.json", import.meta.url),
  pronouns: new URL("../data/pronouns.json", import.meta.url),
  prepositions: new URL("../data/prepositions.json", import.meta.url),
  comparatives: new URL("../data/comparatives.json", import.meta.url),
  word_order: new URL("../data/word_order.json", import.meta.url),
  questions: new URL("../data/questions.json", import.meta.url),
  negation: new URL("../data/negation.json", import.meta.url),
  quantifiers: new URL("../data/quantifiers.json", import.meta.url),
  gerunds_infinitives: new URL("../data/gerunds_infinitives.json", import.meta.url),
  conditionals: new URL("../data/conditionals.json", import.meta.url),
  reported_speech: new URL("../data/reported_speech.json", import.meta.url),
  relative_clauses: new URL("../data/relative_clauses.json", import.meta.url),
  phrasal_verbs: new URL("../data/phrasal_verbs.json", import.meta.url),
  so_such_too_enough: new URL("../data/so_such_too_enough.json", import.meta.url),
  used_to_would: new URL("../data/used_to_would.json", import.meta.url),
  wish_ifonly: new URL("../data/wish_ifonly.json", import.meta.url),
  causative: new URL("../data/causative.json", import.meta.url),
  adjective_order: new URL("../data/adjective_order.json", import.meta.url),
  adverbs: new URL("../data/adverbs.json", import.meta.url),
  future_forms: new URL("../data/future_forms.json", import.meta.url),
  determiners: new URL("../data/determiners.json", import.meta.url),
  linking_words: new URL("../data/linking_words.json", import.meta.url),
  direct_indirect_objects: new URL("../data/direct_indirect_objects.json", import.meta.url),
  participle_clauses: new URL("../data/participle_clauses.json", import.meta.url),
  modals_perfect: new URL("../data/modals_perfect.json", import.meta.url),
  verb_patterns: new URL("../data/verb_patterns.json", import.meta.url),
  inversion: new URL("../data/inversion.json", import.meta.url),
  cleft_sentences: new URL("../data/cleft_sentences.json", import.meta.url),
  ellipsis_substitution: new URL("../data/ellipsis_substitution.json", import.meta.url),
  emphasis: new URL("../data/emphasis.json", import.meta.url),
  subjunctive: new URL("../data/subjunctive.json", import.meta.url),
  word_formation: new URL("../data/word_formation.json", import.meta.url),
  collocations_prepositions: new URL("../data/collocations_prepositions.json", import.meta.url),
  discourse_markers: new URL("../data/discourse_markers.json", import.meta.url),
  british_american: new URL("../data/british_american.json", import.meta.url),
  time_clauses: new URL("../data/time_clauses.json", import.meta.url),
  subject_verb_agreement: new URL("../data/subject_verb_agreement.json", import.meta.url),
  imperatives: new URL("../data/imperatives.json", import.meta.url),
  there_is_are: new URL("../data/there_is_are.json", import.meta.url),
  exclamatives: new URL("../data/exclamatives.json", import.meta.url),
  would_rather_had_better: new URL("../data/would_rather_had_better.json", import.meta.url),
  purpose_clauses: new URL("../data/purpose_clauses.json", import.meta.url),
  passive_reporting: new URL("../data/passive_reporting.json", import.meta.url),
  ing_ed_adjectives: new URL("../data/ing_ed_adjectives.json", import.meta.url),
  partitives: new URL("../data/partitives.json", import.meta.url),
  correlative_conjunctions: new URL("../data/correlative_conjunctions.json", import.meta.url),
  indefinite_pronouns: new URL("../data/indefinite_pronouns.json", import.meta.url),
  modals_deduction: new URL("../data/modals_deduction.json", import.meta.url),
  double_comparatives: new URL("../data/double_comparatives.json", import.meta.url),
  concessive_clauses: new URL("../data/concessive_clauses.json", import.meta.url),
  stative_verbs: new URL("../data/stative_verbs.json", import.meta.url),
  compound_nouns: new URL("../data/compound_nouns.json", import.meta.url),
  degree_adverbs: new URL("../data/degree_adverbs.json", import.meta.url),
  reciprocal_pronouns: new URL("../data/reciprocal_pronouns.json", import.meta.url),
  numbers_dates: new URL("../data/numbers_dates.json", import.meta.url),
  noun_clauses: new URL("../data/noun_clauses.json", import.meta.url),
  litotes: new URL("../data/litotes.json", import.meta.url),
  as_if_as_though: new URL("../data/as_if_as_though.json", import.meta.url),
  nominalization: new URL("../data/nominalization.json", import.meta.url),
  reporting_verb_patterns: new URL("../data/reporting_verb_patterns.json", import.meta.url),
  absolute_clauses: new URL("../data/absolute_clauses.json", import.meta.url),
  modal_passive: new URL("../data/modal_passive.json", import.meta.url),
  complex_prepositions: new URL("../data/complex_prepositions.json", import.meta.url),
  ergative_verbs: new URL("../data/ergative_verbs.json", import.meta.url),
  apposition: new URL("../data/apposition.json", import.meta.url),
  fronting: new URL("../data/fronting.json", import.meta.url),
  focusing_adverbs: new URL("../data/focusing_adverbs.json", import.meta.url),
  get_passive: new URL("../data/get_passive.json", import.meta.url),
  viewpoint_adverbs: new URL("../data/viewpoint_adverbs.json", import.meta.url),
  future_in_the_past: new URL("../data/future_in_the_past.json", import.meta.url),
  relative_clause_prepositions: new URL("../data/relative_clause_prepositions.json", import.meta.url),
  impersonal_pronouns: new URL("../data/impersonal_pronouns.json", import.meta.url),
  comparative_clauses: new URL("../data/comparative_clauses.json", import.meta.url),
  vague_language: new URL("../data/vague_language.json", import.meta.url),
  conditional_conjunctions: new URL("../data/conditional_conjunctions.json", import.meta.url),
  phrasal_verb_passive: new URL("../data/phrasal_verb_passive.json", import.meta.url),
  wh_infinitive: new URL("../data/wh_infinitive.json", import.meta.url),
  relative_clause_reference: new URL("../data/relative_clause_reference.json", import.meta.url),
  characteristic_will_would: new URL("../data/characteristic_will_would.json", import.meta.url),
  modal_remoteness: new URL("../data/modal_remoteness.json", import.meta.url),
  delexicalized_verbs: new URL("../data/delexicalized_verbs.json", import.meta.url),
  free_relative_clauses: new URL("../data/free_relative_clauses.json", import.meta.url),
  perception_causative: new URL("../data/perception_causative.json", import.meta.url),
  adjective_position: new URL("../data/adjective_position.json", import.meta.url),
  imminent_future: new URL("../data/imminent_future.json", import.meta.url),
  anticipatory_object_it: new URL("../data/anticipatory_object_it.json", import.meta.url),
  need_doing: new URL("../data/need_doing.json", import.meta.url),
  there_modals: new URL("../data/there_modals.json", import.meta.url),
  need_dare: new URL("../data/need_dare.json", import.meta.url),
  ditransitive_passive: new URL("../data/ditransitive_passive.json", import.meta.url),
  as_vs_like: new URL("../data/as_vs_like.json", import.meta.url),
  result_clauses: new URL("../data/result_clauses.json", import.meta.url),
  formal_connectors: new URL("../data/formal_connectors.json", import.meta.url),
  progressive_comparatives: new URL("../data/progressive_comparatives.json", import.meta.url),
  verbless_clauses: new URL("../data/verbless_clauses.json", import.meta.url),
  infinitive_postmodifiers: new URL("../data/infinitive_postmodifiers.json", import.meta.url),
  dislocation: new URL("../data/dislocation.json", import.meta.url),
  rhetorical_questions: new URL("../data/rhetorical_questions.json", import.meta.url),
  raising_verbs: new URL("../data/raising_verbs.json", import.meta.url),
  tough_movement: new URL("../data/tough_movement.json", import.meta.url),
  split_infinitive: new URL("../data/split_infinitive.json", import.meta.url),
  floating_quantifiers: new URL("../data/floating_quantifiers.json", import.meta.url),
  nominal_adjectives: new URL("../data/nominal_adjectives.json", import.meta.url),
  rhetorical_comparison: new URL("../data/rhetorical_comparison.json", import.meta.url),
  for_to_infinitive: new URL("../data/for_to_infinitive.json", import.meta.url),
  comment_clauses: new URL("../data/comment_clauses.json", import.meta.url),
  perfect_infinitive_gerund: new URL("../data/perfect_infinitive_gerund.json", import.meta.url),
  possessive_gerund: new URL("../data/possessive_gerund.json", import.meta.url),
  gapping_stripping: new URL("../data/gapping_stripping.json", import.meta.url),
  object_complements: new URL("../data/object_complements.json", import.meta.url),
  unreal_past: new URL("../data/unreal_past.json", import.meta.url),
  formal_reference: new URL("../data/formal_reference.json", import.meta.url),
  generic_reference: new URL("../data/generic_reference.json", import.meta.url),
  whether_or_clauses: new URL("../data/whether_or_clauses.json", import.meta.url),
  but_for_without: new URL("../data/but_for_without.json", import.meta.url),
  emphatic_own: new URL("../data/emphatic_own.json", import.meta.url),
  might_as_well: new URL("../data/might_as_well.json", import.meta.url),
  so_such_inversion: new URL("../data/so_such_inversion.json", import.meta.url),
  reason_clauses: new URL("../data/reason_clauses.json", import.meta.url),
  modals_perfect_continuous: new URL("../data/modals_perfect_continuous.json", import.meta.url),
  compound_adjectives: new URL("../data/compound_adjectives.json", import.meta.url),
  elative: new URL("../data/elative.json", import.meta.url),
  multiplicative_comparison: new URL("../data/multiplicative_comparison.json", import.meta.url),
  indefinite_article_inversion: new URL("../data/indefinite_article_inversion.json", import.meta.url),
  verb_object_ing: new URL("../data/verb_object_ing.json", import.meta.url),
  headline_language: new URL("../data/headline_language.json", import.meta.url),
  question_prepositions: new URL("../data/question_prepositions.json", import.meta.url),
  shall_modality: new URL("../data/shall_modality.json", import.meta.url),
  manner_clauses: new URL("../data/manner_clauses.json", import.meta.url),
  binomial_expressions: new URL("../data/binomial_expressions.json", import.meta.url),
  measure_genitive: new URL("../data/measure_genitive.json", import.meta.url),
  place_clauses: new URL("../data/place_clauses.json", import.meta.url),
  past_ability: new URL("../data/past_ability.json", import.meta.url),
  sentential_as: new URL("../data/sentential_as.json", import.meta.url),
  transferred_negation: new URL("../data/transferred_negation.json", import.meta.url),
  free_indirect_speech: new URL("../data/free_indirect_speech.json", import.meta.url),
  historic_present: new URL("../data/historic_present.json", import.meta.url),
  tag_questions: new URL("../data/tag_questions.json", import.meta.url),
  passive_infinitive_gerund: new URL("../data/passive_infinitive_gerund.json", import.meta.url),
  supposed_meant_to: new URL("../data/supposed_meant_to.json", import.meta.url),
  echo_questions: new URL("../data/echo_questions.json", import.meta.url),
  heavy_np_shift: new URL("../data/heavy_np_shift.json", import.meta.url),
  parallel_structure: new URL("../data/parallel_structure.json", import.meta.url),
  contrastive_while_whereas: new URL("../data/contrastive_while_whereas.json", import.meta.url),
  situational_ellipsis: new URL("../data/situational_ellipsis.json", import.meta.url),
  invariable_nouns: new URL("../data/invariable_nouns.json", import.meta.url),
  coordinating_conjunctions: new URL("../data/coordinating_conjunctions.json", import.meta.url),
  way_construction: new URL("../data/way_construction.json", import.meta.url),
  formal_compound_adverbs: new URL("../data/formal_compound_adverbs.json", import.meta.url),
  evaluative_binominal: new URL("../data/evaluative_binominal.json", import.meta.url),
  quantity_phrases: new URL("../data/quantity_phrases.json", import.meta.url),
  group_genitive: new URL("../data/group_genitive.json", import.meta.url),
  classical_plurals: new URL("../data/classical_plurals.json", import.meta.url),
  infinitive_ellipsis: new URL("../data/infinitive_ellipsis.json", import.meta.url),
};

const DRILLS_URLS = {
  tenses: new URL("../data/tenseDrills.json", import.meta.url),
  articles: new URL("../data/articleDrills.json", import.meta.url),
  modals: new URL("../data/modalDrills.json", import.meta.url),
  passive: new URL("../data/passiveDrills.json", import.meta.url),
  plurals: new URL("../data/pluralsDrills.json", import.meta.url),
  possessives: new URL("../data/possessivesDrills.json", import.meta.url),
  pronouns: new URL("../data/pronounsDrills.json", import.meta.url),
  prepositions: new URL("../data/prepositionsDrills.json", import.meta.url),
  comparatives: new URL("../data/comparativesDrills.json", import.meta.url),
  word_order: new URL("../data/word_orderDrills.json", import.meta.url),
  questions: new URL("../data/questionsDrills.json", import.meta.url),
  negation: new URL("../data/negationDrills.json", import.meta.url),
  quantifiers: new URL("../data/quantifiersDrills.json", import.meta.url),
  gerunds_infinitives: new URL("../data/gerunds_infinitivesDrills.json", import.meta.url),
  conditionals: new URL("../data/conditionalsDrills.json", import.meta.url),
  reported_speech: new URL("../data/reported_speechDrills.json", import.meta.url),
  relative_clauses: new URL("../data/relative_clausesDrills.json", import.meta.url),
  phrasal_verbs: new URL("../data/phrasal_verbsDrills.json", import.meta.url),
  so_such_too_enough: new URL("../data/so_such_too_enoughDrills.json", import.meta.url),
  used_to_would: new URL("../data/used_to_wouldDrills.json", import.meta.url),
  wish_ifonly: new URL("../data/wish_ifonlyDrills.json", import.meta.url),
  causative: new URL("../data/causativeDrills.json", import.meta.url),
  adjective_order: new URL("../data/adjective_orderDrills.json", import.meta.url),
  adverbs: new URL("../data/adverbsDrills.json", import.meta.url),
  future_forms: new URL("../data/future_formsDrills.json", import.meta.url),
  determiners: new URL("../data/determinersDrills.json", import.meta.url),
  linking_words: new URL("../data/linking_wordsDrills.json", import.meta.url),
  direct_indirect_objects: new URL("../data/direct_indirect_objectsDrills.json", import.meta.url),
  participle_clauses: new URL("../data/participle_clausesDrills.json", import.meta.url),
  modals_perfect: new URL("../data/modals_perfectDrills.json", import.meta.url),
  verb_patterns: new URL("../data/verb_patternsDrills.json", import.meta.url),
  inversion: new URL("../data/inversionDrills.json", import.meta.url),
  cleft_sentences: new URL("../data/cleft_sentencesDrills.json", import.meta.url),
  ellipsis_substitution: new URL("../data/ellipsis_substitutionDrills.json", import.meta.url),
  emphasis: new URL("../data/emphasisDrills.json", import.meta.url),
  subjunctive: new URL("../data/subjunctiveDrills.json", import.meta.url),
  word_formation: new URL("../data/word_formationDrills.json", import.meta.url),
  collocations_prepositions: new URL("../data/collocations_prepositionsDrills.json", import.meta.url),
  discourse_markers: new URL("../data/discourse_markersDrills.json", import.meta.url),
  british_american: new URL("../data/british_americanDrills.json", import.meta.url),
  time_clauses: new URL("../data/time_clausesDrills.json", import.meta.url),
  subject_verb_agreement: new URL("../data/subject_verb_agreementDrills.json", import.meta.url),
  imperatives: new URL("../data/imperativesDrills.json", import.meta.url),
  there_is_are: new URL("../data/there_is_areDrills.json", import.meta.url),
  exclamatives: new URL("../data/exclamativesDrills.json", import.meta.url),
  would_rather_had_better: new URL("../data/would_rather_had_betterDrills.json", import.meta.url),
  purpose_clauses: new URL("../data/purpose_clausesDrills.json", import.meta.url),
  passive_reporting: new URL("../data/passive_reportingDrills.json", import.meta.url),
  ing_ed_adjectives: new URL("../data/ing_ed_adjectivesDrills.json", import.meta.url),
  partitives: new URL("../data/partitivesDrills.json", import.meta.url),
  correlative_conjunctions: new URL("../data/correlative_conjunctionsDrills.json", import.meta.url),
  indefinite_pronouns: new URL("../data/indefinite_pronounsDrills.json", import.meta.url),
  modals_deduction: new URL("../data/modals_deductionDrills.json", import.meta.url),
  double_comparatives: new URL("../data/double_comparativesDrills.json", import.meta.url),
  concessive_clauses: new URL("../data/concessive_clausesDrills.json", import.meta.url),
  stative_verbs: new URL("../data/stative_verbsDrills.json", import.meta.url),
  compound_nouns: new URL("../data/compound_nounsDrills.json", import.meta.url),
  degree_adverbs: new URL("../data/degree_adverbsDrills.json", import.meta.url),
  reciprocal_pronouns: new URL("../data/reciprocal_pronounsDrills.json", import.meta.url),
  numbers_dates: new URL("../data/numbers_datesDrills.json", import.meta.url),
  noun_clauses: new URL("../data/noun_clausesDrills.json", import.meta.url),
  litotes: new URL("../data/litotesDrills.json", import.meta.url),
  as_if_as_though: new URL("../data/as_if_as_thoughDrills.json", import.meta.url),
  nominalization: new URL("../data/nominalizationDrills.json", import.meta.url),
  reporting_verb_patterns: new URL("../data/reporting_verb_patternsDrills.json", import.meta.url),
  absolute_clauses: new URL("../data/absolute_clausesDrills.json", import.meta.url),
  modal_passive: new URL("../data/modal_passiveDrills.json", import.meta.url),
  complex_prepositions: new URL("../data/complex_prepositionsDrills.json", import.meta.url),
  ergative_verbs: new URL("../data/ergative_verbsDrills.json", import.meta.url),
  apposition: new URL("../data/appositionDrills.json", import.meta.url),
  fronting: new URL("../data/frontingDrills.json", import.meta.url),
  focusing_adverbs: new URL("../data/focusing_adverbsDrills.json", import.meta.url),
  get_passive: new URL("../data/get_passiveDrills.json", import.meta.url),
  viewpoint_adverbs: new URL("../data/viewpoint_adverbsDrills.json", import.meta.url),
  future_in_the_past: new URL("../data/future_in_the_pastDrills.json", import.meta.url),
  relative_clause_prepositions: new URL("../data/relative_clause_prepositionsDrills.json", import.meta.url),
  impersonal_pronouns: new URL("../data/impersonal_pronounsDrills.json", import.meta.url),
  comparative_clauses: new URL("../data/comparative_clausesDrills.json", import.meta.url),
  vague_language: new URL("../data/vague_languageDrills.json", import.meta.url),
  conditional_conjunctions: new URL("../data/conditional_conjunctionsDrills.json", import.meta.url),
  phrasal_verb_passive: new URL("../data/phrasal_verb_passiveDrills.json", import.meta.url),
  wh_infinitive: new URL("../data/wh_infinitiveDrills.json", import.meta.url),
  relative_clause_reference: new URL("../data/relative_clause_referenceDrills.json", import.meta.url),
  characteristic_will_would: new URL("../data/characteristic_will_wouldDrills.json", import.meta.url),
  modal_remoteness: new URL("../data/modal_remotenessDrills.json", import.meta.url),
  delexicalized_verbs: new URL("../data/delexicalized_verbsDrills.json", import.meta.url),
  free_relative_clauses: new URL("../data/free_relative_clausesDrills.json", import.meta.url),
  perception_causative: new URL("../data/perception_causativeDrills.json", import.meta.url),
  adjective_position: new URL("../data/adjective_positionDrills.json", import.meta.url),
  imminent_future: new URL("../data/imminent_futureDrills.json", import.meta.url),
  anticipatory_object_it: new URL("../data/anticipatory_object_itDrills.json", import.meta.url),
  need_doing: new URL("../data/need_doingDrills.json", import.meta.url),
  there_modals: new URL("../data/there_modalsDrills.json", import.meta.url),
  need_dare: new URL("../data/need_dareDrills.json", import.meta.url),
  ditransitive_passive: new URL("../data/ditransitive_passiveDrills.json", import.meta.url),
  as_vs_like: new URL("../data/as_vs_likeDrills.json", import.meta.url),
  result_clauses: new URL("../data/result_clausesDrills.json", import.meta.url),
  formal_connectors: new URL("../data/formal_connectorsDrills.json", import.meta.url),
  progressive_comparatives: new URL("../data/progressive_comparativesDrills.json", import.meta.url),
  verbless_clauses: new URL("../data/verbless_clausesDrills.json", import.meta.url),
  infinitive_postmodifiers: new URL("../data/infinitive_postmodifiersDrills.json", import.meta.url),
  dislocation: new URL("../data/dislocationDrills.json", import.meta.url),
  rhetorical_questions: new URL("../data/rhetorical_questionsDrills.json", import.meta.url),
  raising_verbs: new URL("../data/raising_verbsDrills.json", import.meta.url),
  tough_movement: new URL("../data/tough_movementDrills.json", import.meta.url),
  split_infinitive: new URL("../data/split_infinitiveDrills.json", import.meta.url),
  floating_quantifiers: new URL("../data/floating_quantifiersDrills.json", import.meta.url),
  nominal_adjectives: new URL("../data/nominal_adjectivesDrills.json", import.meta.url),
  rhetorical_comparison: new URL("../data/rhetorical_comparisonDrills.json", import.meta.url),
  for_to_infinitive: new URL("../data/for_to_infinitiveDrills.json", import.meta.url),
  comment_clauses: new URL("../data/comment_clausesDrills.json", import.meta.url),
  perfect_infinitive_gerund: new URL("../data/perfect_infinitive_gerundDrills.json", import.meta.url),
  possessive_gerund: new URL("../data/possessive_gerundDrills.json", import.meta.url),
  gapping_stripping: new URL("../data/gapping_strippingDrills.json", import.meta.url),
  object_complements: new URL("../data/object_complementsDrills.json", import.meta.url),
  unreal_past: new URL("../data/unreal_pastDrills.json", import.meta.url),
  formal_reference: new URL("../data/formal_referenceDrills.json", import.meta.url),
  generic_reference: new URL("../data/generic_referenceDrills.json", import.meta.url),
  whether_or_clauses: new URL("../data/whether_or_clausesDrills.json", import.meta.url),
  but_for_without: new URL("../data/but_for_withoutDrills.json", import.meta.url),
  emphatic_own: new URL("../data/emphatic_ownDrills.json", import.meta.url),
  might_as_well: new URL("../data/might_as_wellDrills.json", import.meta.url),
  so_such_inversion: new URL("../data/so_such_inversionDrills.json", import.meta.url),
  reason_clauses: new URL("../data/reason_clausesDrills.json", import.meta.url),
  modals_perfect_continuous: new URL("../data/modals_perfect_continuousDrills.json", import.meta.url),
  compound_adjectives: new URL("../data/compound_adjectivesDrills.json", import.meta.url),
  elative: new URL("../data/elativeDrills.json", import.meta.url),
  multiplicative_comparison: new URL("../data/multiplicative_comparisonDrills.json", import.meta.url),
  indefinite_article_inversion: new URL("../data/indefinite_article_inversionDrills.json", import.meta.url),
  verb_object_ing: new URL("../data/verb_object_ingDrills.json", import.meta.url),
  headline_language: new URL("../data/headline_languageDrills.json", import.meta.url),
  question_prepositions: new URL("../data/question_prepositionsDrills.json", import.meta.url),
  shall_modality: new URL("../data/shall_modalityDrills.json", import.meta.url),
  manner_clauses: new URL("../data/manner_clausesDrills.json", import.meta.url),
  binomial_expressions: new URL("../data/binomial_expressionsDrills.json", import.meta.url),
  measure_genitive: new URL("../data/measure_genitiveDrills.json", import.meta.url),
  place_clauses: new URL("../data/place_clausesDrills.json", import.meta.url),
  past_ability: new URL("../data/past_abilityDrills.json", import.meta.url),
  sentential_as: new URL("../data/sentential_asDrills.json", import.meta.url),
  transferred_negation: new URL("../data/transferred_negationDrills.json", import.meta.url),
  free_indirect_speech: new URL("../data/free_indirect_speechDrills.json", import.meta.url),
  historic_present: new URL("../data/historic_presentDrills.json", import.meta.url),
  tag_questions: new URL("../data/tag_questionsDrills.json", import.meta.url),
  passive_infinitive_gerund: new URL("../data/passive_infinitive_gerundDrills.json", import.meta.url),
  supposed_meant_to: new URL("../data/supposed_meant_toDrills.json", import.meta.url),
  echo_questions: new URL("../data/echo_questionsDrills.json", import.meta.url),
  heavy_np_shift: new URL("../data/heavy_np_shiftDrills.json", import.meta.url),
  parallel_structure: new URL("../data/parallel_structureDrills.json", import.meta.url),
  contrastive_while_whereas: new URL("../data/contrastive_while_whereasDrills.json", import.meta.url),
  situational_ellipsis: new URL("../data/situational_ellipsisDrills.json", import.meta.url),
  invariable_nouns: new URL("../data/invariable_nounsDrills.json", import.meta.url),
  coordinating_conjunctions: new URL("../data/coordinating_conjunctionsDrills.json", import.meta.url),
  way_construction: new URL("../data/way_constructionDrills.json", import.meta.url),
  formal_compound_adverbs: new URL("../data/formal_compound_adverbsDrills.json", import.meta.url),
  evaluative_binominal: new URL("../data/evaluative_binominalDrills.json", import.meta.url),
  quantity_phrases: new URL("../data/quantity_phrasesDrills.json", import.meta.url),
  group_genitive: new URL("../data/group_genitiveDrills.json", import.meta.url),
  classical_plurals: new URL("../data/classical_pluralsDrills.json", import.meta.url),
  infinitive_ellipsis: new URL("../data/infinitive_ellipsisDrills.json", import.meta.url),
};

let cachedTopics = null;
const theoryCache = new Map();
const drillsCache = new Map();

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Nie udało się wczytać danych gramatyki (HTTP ${res.status})`);
  }
  return res.json();
}

export async function loadTopics() {
  if (!cachedTopics) cachedTopics = await fetchJson(TOPICS_URL);
  return cachedTopics;
}

export async function loadTopicTheory(topicId) {
  if (!theoryCache.has(topicId)) {
    theoryCache.set(topicId, await fetchJson(THEORY_URLS[topicId]));
  }
  return theoryCache.get(topicId);
}

export async function loadTopicDrills(topicId) {
  if (!drillsCache.has(topicId)) {
    drillsCache.set(topicId, await fetchJson(DRILLS_URLS[topicId]));
  }
  return drillsCache.get(topicId);
}
